spring.application.name=tbits-ai

server.port=8080

# =========================
# OpenAI
# =========================
openai.api.key=${OPENAI_API_KEY}

# =========================
# Milvus
# =========================
milvus.url=http://204.168.175.115:19530
milvus.token=root:Milvus
milvus.collection=openai_data_collection

# =========================
# Embedding
# =========================
embedding.dimension=3072

# =========================
# Upload Limits
# =========================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

